Task builder
CS2103JAN2017-W09-B2/main pull request #24
Opened 2017-03-11 15:54 UTC by sharkey1314

Added TaskBuilder class to support flexible building of tasks

- new Task.TaskBuilder().setName("name").build();
- new Task.TaskBuilder().setName("name").setDate("date").addTags("tag").build()
- new Task.TaskBuilder(ReadOnlyTask task).setName("newName").build()

Allows optional attributes, modifying tasks

2017-03-11 15:55 UTC, sharkey1314 commented
I commented some tests out because it's glitchy and not consistent with the new add command somehow :/

2017-03-12 10:06 UTC, pyxyyy commented on src/main/java/seedu/typed/model/task/Task.java
> +        public TaskBuilder setName(String name) {
throw IVE as well?

2017-03-12 10:34 UTC, pyxyyy commented on src/test/java/guitests/EditCommandTest.java
> -        assertResultMessage(Name.MESSAGE_NAME_CONSTRAINTS);
keep this test by commenting it out instead?

2017-03-12 10:42 UTC, pyxyyy requested changes
left a few comments under the original code as well, all fairly minor details. taskbuilder looks good!

2017-03-12 10:42 UTC, pyxyyy commented on src/test/java/seedu/typed/logic/LogicManagerTest.java
> -        assertCommandFailure("add []\\[;] d/12/34/5678", Name.MESSAGE_NAME_CONSTRAINTS);
keep this test by commenting it out instead?

2017-03-12 10:42 UTC, pyxyyy commented on src/main/java/seedu/typed/model/task/Task.java
> +     */
maybe consider separating TaskBuilder from Task (add an extra file)?

2017-03-12 13:37 UTC, merged